### ISSUE TITLE
missing repo functx

### ISSUE THREAD

**Issue by vibolseng** [chartes/dots#28]
Bonjour,

je suis peut-etre passé à côté de ça dans la doc, mais le dépot "functx" n'est à priori pas dans basex par défaut. 
Je propose de rajouter cette information dans la doc avec le lien vers la documentation basex https://docs.basex.org/main/Repository et la commande pour l'installer (https://docs.basex.org/main/Commands#repo_install).

j'ai dû faire la manip avec la version basex standalone et le basex.war (sous ubuntu).

**Comment by philippepons** [comment]
Bonjour,
Et merci pour ce retour.

En réalité, la présence du dépôt "functx" dans BaseX dépend de l'installation du logiciel. Avec DoTS, nous recommandons d'installer BaseX avec le zip (cf. documentation: https://chartes.github.io/dots_documentation/#install) qui fournit la version la plus complète y compris le dépôt "functx".
